In [3]:
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.cross_validation import train_test_split
from sklearn.metrics.pairwise import euclidean_distances
from sklearn.metrics import accuracy_score
import numpy as ny
from numpy import *
from collections import Counter
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn import datasets
from sklearn.preprocessing import MinMaxScaler


def calculateProbability(x, mean, stdev):
    exponent = math.exp(-(math.pow(x-mean,2)/(2*math.pow(stdev,2))))
    return (1 / (math.sqrt(2*math.pi) * stdev)) * exponent

def separateByClass(dataset,classes):
    separated = {}
    for i in range(len(dataset)):
        curr_class = classes[i];
        if (curr_class not in separated):
            separated[curr_class] = []
        separated[curr_class].append(dataset[i])
    return separated

from sklearn import datasets
iris = datasets.load_iris()
#print(iris)

In [5]:

data = iris["data"]
labels = iris["target"]

scaler = StandardScaler()
scaled_data = scaler.fit_transform(iris.data)
print("Scaled data",scaled_data[0:10,:])

norm_data = MinMaxScaler().fit_transform(data)
print("Norm data",norm_data[0:10,:])

Scaled data [[-0.90068117  1.03205722 -1.3412724  -1.31297673]
 [-1.14301691 -0.1249576  -1.3412724  -1.31297673]
 [-1.38535265  0.33784833 -1.39813811 -1.31297673]
 [-1.50652052  0.10644536 -1.2844067  -1.31297673]
 [-1.02184904  1.26346019 -1.3412724  -1.31297673]
 [-0.53717756  1.95766909 -1.17067529 -1.05003079]
 [-1.50652052  0.80065426 -1.3412724  -1.18150376]
 [-1.02184904  0.80065426 -1.2844067  -1.31297673]
 [-1.74885626 -0.35636057 -1.3412724  -1.31297673]
 [-1.14301691  0.10644536 -1.2844067  -1.4444497 ]]
Norm data [[ 0.22222222  0.625       0.06779661  0.04166667]
 [ 0.16666667  0.41666667  0.06779661  0.04166667]
 [ 0.11111111  0.5         0.05084746  0.04166667]
 [ 0.08333333  0.45833333  0.08474576  0.04166667]
 [ 0.19444444  0.66666667  0.06779661  0.04166667]
 [ 0.30555556  0.79166667  0.11864407  0.125     ]
 [ 0.08333333  0.58333333  0.06779661  0.08333333]
 [ 0.19444444  0.58333333  0.08474576  0.04166667]
 [ 0.02777778  0.375       0.06779661  0.04166667]
 [ 0.166